# Generated by Django 4.2.20 on 2025-04-30 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "collection_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัส Collection",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ชื่อ Collection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatabaseSubscription",
            fields=[
                (
                    "DS_ID",
                    models.AutoField(
                        db_column="DS_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสของฐานข้อมูล",
                    ),
                ),
                (
                    "DB_Name",
                    models.CharField(
                        db_column="DB_Name",
                        max_length=255,
                        verbose_name="ชื่อฐานข้อมูล",
                    ),
                ),
                (
                    "DBJournal_List",
                    models.TextField(
                        blank=True,
                        db_column="DBJournal_List",
                        null=True,
                        verbose_name="จำนวนชื่อเรื่องแบบวารสาร",
                    ),
                ),
                (
                    "DBEBook_List",
                    models.TextField(
                        blank=True,
                        db_column="DBEBook_List",
                        null=True,
                        verbose_name="จำนวนชื่อเรื่องแบบ E-Books",
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="วันที่เริ่มต้นการบอกรับ"
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="วันที่สิ้นสุดการบอกรับ"
                    ),
                ),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="กำหนดการต่ออายุการบอกรับ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่สร้าง"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="สถานะการบอกรับ"),
                ),
                (
                    "has_perpetual_license",
                    models.BooleanField(
                        default=False, verbose_name="มีสิทธิ์การใช้งานถาวร"
                    ),
                ),
                (
                    "perpetual_license_terms",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="เงื่อนไขสิทธิ์การใช้งานถาวร",
                    ),
                ),
                (
                    "concurrent_users",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="จำนวนผู้ใช้งานพร้อมกัน"
                    ),
                ),
                (
                    "remote_access_allowed",
                    models.BooleanField(
                        default=False, verbose_name="อนุญาตการเข้าถึงจากภายนอก"
                    ),
                ),
                (
                    "download_allowed",
                    models.BooleanField(
                        default=False, verbose_name="อนุญาตการดาวน์โหลด"
                    ),
                ),
                (
                    "print_allowed",
                    models.BooleanField(default=False, verbose_name="อนุญาตการพิมพ์"),
                ),
                (
                    "copy_allowed",
                    models.BooleanField(default=False, verbose_name="อนุญาตการทำสำเนา"),
                ),
                (
                    "interlibrary_loan_allowed",
                    models.BooleanField(
                        default=False,
                        verbose_name="บริการยืมทรัพยากรระหว่างห้องสมุด (ILL)",
                    ),
                ),
                (
                    "usage_conditions_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="เงื่อนไขการใช้งานอื่นๆ"
                    ),
                ),
                (
                    "license_agreement_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="licenses/",
                        verbose_name="ไฟล์ข้อตกลงสิทธิ์การใช้งาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "ฐานข้อมูลที่บอกรับ",
                "verbose_name_plural": "ฐานข้อมูลที่บอกรับ",
                "db_table": "Database_Subscription",
                "ordering": ["DB_Name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceLevelOperation",
            fields=[
                (
                    "slo_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="รหัสบริการ"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ชื่อบริการ"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="คำอธิบายบริการ"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ค่าบริการ",
                    ),
                ),
            ],
            options={
                "verbose_name": "บริการเพิ่มเติม",
                "verbose_name_plural": "บริการเพิ่มเติม",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "subscriber_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="รหัสหน่วยงาน"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อหน่วยงาน")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="รหัสห้องสมุด",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("central_lib", "หอสมุดกลาง สำนักงานวิทยทรัพยากร"),
                            ("fac", "ห้องสมุดคณะสถาปัตยกรรมศาสตร์"),
                            ("far", "ห้องสมุดคณะอักษรศาสตร์"),
                            (
                                "cun",
                                "ศูนย์เครือข่ายการเรียนรู้เพื่อภูมิภาค แห่งจุฬาลงกรณ์มหาวิทยาลัย : จังหวัดน่าน",
                            ),
                            ("fca", "ห้องสมุดคณะพาณิชยศาสตร์และการบัญชี"),
                            ("fpu", "ห้องสมุดวิทยาลัยวิทยาศาสตร์สาธารณสุข"),
                            ("fco", "ห้องสมุดคณะนิเทศศาสตร์"),
                            ("cuh", "หอประวัติ จุฬาลงกรณ์มหาวิทยาลัย"),
                            ("fde", "ห้องสมุดคณะทันตแพทยศาสตร์"),
                            ("dha", "ห้องสมุดธรรมสถาน"),
                            ("fec", "ศูนย์บรรณสารสนเทศ คณะเศรษฐศาสตร์"),
                            ("fed", "ศูนย์บรรณสารสนเทศทางการศึกษา คณะครุศาสตร์"),
                            ("fen", "ห้องสมุดคณะวิศวกรรมศาสตร์"),
                            ("ffa", "ห้องสมุดคณะศิลปกรรมศาสตร์"),
                            ("fli", "ห้องสมุดสถาบันภาษา"),
                            ("fla", "ศูนย์เพชรรัตนนิติทรัพยากร คณะนิติศาสตร์"),
                            ("fme", "หอสมุดคณะแพทยศาสตร์"),
                            (
                                "fpc",
                                "ศูนย์ข้อมูลอัจฉริยะกำจัด มงคลกุล เพื่ออุตสาหกรรมปิโตรเลียมและปิโตรเคมี",
                            ),
                            ("fph", "ห้องสมุดคณะเภสัชศาสตร์"),
                            ("fps", "ห้องสมุดคณะรัฐศาสตร์"),
                            ("fss", "ห้องสมุดสถาบันบัณฑิตบริหารธุรกิจ ศศินทร์"),
                            ("fs", "ห้องสมุดคณะวิทยาศาสตร์"),
                            (
                                "tai",
                                "ศูนย์สารสนเทศประเทศไทยและประชาคมอาเซียน สำนักงานวิทยทรัพยากร",
                            ),
                            ("fvs", "ห้องสมุดและเอกสารการสัตว์ คณะสัตวแพทยศาสตร์"),
                            ("other", "อื่นๆ"),
                        ],
                        default="central_lib",
                        max_length=20,
                        verbose_name="ประเภทหน่วยงาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "หน่วยงานผู้รับบริการ",
                "verbose_name_plural": "หน่วยงานผู้รับบริการ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "Vendor_ID",
                    models.AutoField(
                        db_column="Vendor_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสผู้ขาย",
                    ),
                ),
                (
                    "Vendor_Name",
                    models.CharField(
                        db_column="Vendor_Name",
                        max_length=255,
                        verbose_name="ชื่อผู้ขาย",
                    ),
                ),
                (
                    "Contact_Person",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ผู้ติดต่อ"
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="อีเมล"
                    ),
                ),
                (
                    "Phone_Number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="เบอร์โทรศัพท์",
                    ),
                ),
                (
                    "Address",
                    models.TextField(blank=True, null=True, verbose_name="ที่อยู่"),
                ),
            ],
            options={
                "verbose_name": "ผู้ขาย",
                "verbose_name_plural": "ผู้ขาย",
                "db_table": "Vendor",
                "ordering": ["Vendor_Name"],
            },
        ),
        migrations.CreateModel(
            name="VendorArchive",
            fields=[
                (
                    "Vendor_ID",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสผู้ขาย (ตอน Archive)",
                    ),
                ),
                (
                    "Vendor_Name",
                    models.CharField(
                        max_length=255, verbose_name="ชื่อผู้ขาย (ตอน Archive)"
                    ),
                ),
                (
                    "Contact_Person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ผู้ติดต่อ (ตอน Archive)",
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="อีเมล (ตอน Archive)",
                    ),
                ),
                (
                    "Phone_Number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="เบอร์โทรศัพท์ (ตอน Archive)",
                    ),
                ),
                (
                    "Address",
                    models.TextField(
                        blank=True, null=True, verbose_name="ที่อยู่ (ตอน Archive)"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="วันที่/เวลาที่ Archive",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ปีที่ Archive"
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติผู้ขาย",
                "verbose_name_plural": "ประวัติผู้ขาย",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสการชำระเงิน",
                    ),
                ),
                (
                    "billing_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="จำนวนเงินที่เรียกเก็บ",
                    ),
                ),
                (
                    "billing_currency",
                    models.CharField(
                        choices=[
                            ("THB", "บาทไทย (THB)"),
                            ("USD", "ดอลลาร์สหรัฐ (USD)"),
                            ("EUR", "ยูโร (EUR)"),
                        ],
                        default="THB",
                        max_length=3,
                        verbose_name="สกุลเงินที่เรียกเก็บ",
                    ),
                ),
                (
                    "billing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="วันที่ออกบิล"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="วันที่ชำระเงิน"
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="จำนวนเงินที่ชำระจริง",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="วิธีการชำระเงิน",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="รหัสธุรกรรม",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "รอชำระ"),
                            ("paid", "ชำระแล้ว"),
                            ("overdue", "ค้างชำระ"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะการชำระเงิน",
                    ),
                ),
                (
                    "invoice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="ไฟล์ใบแจ้งหนี้/ใบเสร็จ",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="database_subscription.databasesubscription",
                        verbose_name="ฐานข้อมูลที่บอกรับ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatabaseSubscriptionChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="วันที่/เวลาที่เปลี่ยนแปลง",
                    ),
                ),
                (
                    "change_details",
                    models.JSONField(
                        blank=True, null=True, verbose_name="รายละเอียดการเปลี่ยนแปลง"
                    ),
                ),
                (
                    "database_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="database_subscription.databasesubscription",
                        verbose_name="รหัสของฐานข้อมูล",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติการเปลี่ยนแปลงฐานข้อมูลที่บอกรับ",
                "verbose_name_plural": "ประวัติการเปลี่ยนแปลงฐานข้อมูลที่บอกรับ",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="Vendor_ID",
            field=models.ForeignKey(
                db_column="Vendor_ID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database_subscription.vendor",
                verbose_name="รหัสผู้ขาย",
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="collections",
            field=models.ManyToManyField(
                blank=True,
                to="database_subscription.collection",
                verbose_name="Collections",
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="service_level_operations",
            field=models.ManyToManyField(
                blank=True,
                to="database_subscription.serviceleveloperation",
                verbose_name="บริการเพิ่มเติม",
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="subscribers",
            field=models.ManyToManyField(
                to="database_subscription.subscriber",
                verbose_name="หน่วยงานผู้รับบริการ",
            ),
        ),
        migrations.CreateModel(
            name="YearlyDatabaseSubscriptionArchive",
            fields=[
                (
                    "archive_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="รหัสประวัติ"
                    ),
                ),
                (
                    "database_subscription_id",
                    models.IntegerField(verbose_name="รหัสของฐานข้อมูล (ตอน Archive)"),
                ),
                (
                    "DB_Name",
                    models.CharField(
                        db_column="DB_Name",
                        max_length=255,
                        verbose_name="ชื่อฐานข้อมูล (ตอน Archive)",
                    ),
                ),
                (
                    "collections",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Collections (ตอน Archive)",
                    ),
                ),
                (
                    "DBJournal_List",
                    models.TextField(
                        blank=True,
                        db_column="DBJournal_List",
                        null=True,
                        verbose_name="จำนวนชื่อเรื่องแบบวารสาร (ตอน Archive)",
                    ),
                ),
                (
                    "DBEBook_List",
                    models.TextField(
                        blank=True,
                        db_column="DBEBook_List",
                        null=True,
                        verbose_name="จำนวนชื่อเรื่องแบบ E-Books (ตอน Archive)",
                    ),
                ),
                (
                    "subscription_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="วันที่เริ่มต้นการบอกรับ (ตอน Archive)",
                    ),
                ),
                (
                    "subscription_end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="วันที่สิ้นสุดการบอกรับ (ตอน Archive)",
                    ),
                ),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="กำหนดการต่ออายุการบอกรับ (ตอน Archive)",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="วันที่/เวลาที่ Archive",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="ปีที่ Archive")),
                (
                    "has_perpetual_license",
                    models.BooleanField(
                        default=False,
                        verbose_name="มีสิทธิ์การใช้งานถาวร (ตอน Archive)",
                    ),
                ),
                (
                    "perpetual_license_terms",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="เงื่อนไขสิทธิ์การใช้งานถาวร (ตอน Archive)",
                    ),
                ),
                (
                    "concurrent_users",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนผู้ใช้งานพร้อมกัน (ตอน Archive)",
                    ),
                ),
                (
                    "remote_access_allowed",
                    models.BooleanField(
                        default=False,
                        verbose_name="อนุญาตการเข้าถึงจากภายนอก (ตอน Archive)",
                    ),
                ),
                (
                    "download_allowed",
                    models.BooleanField(
                        default=False, verbose_name="อนุญาตการดาวน์โหลด (ตอน Archive)"
                    ),
                ),
                (
                    "print_allowed",
                    models.BooleanField(
                        default=False, verbose_name="อนุญาตการพิมพ์ (ตอน Archive)"
                    ),
                ),
                (
                    "copy_allowed",
                    models.BooleanField(
                        default=False, verbose_name="อนุญาตการทำสำเนา (ตอน Archive)"
                    ),
                ),
                (
                    "interlibrary_loan_allowed",
                    models.BooleanField(
                        default=False,
                        verbose_name="อนุญาตการยืมระหว่างห้องสมุด (ตอน Archive)",
                    ),
                ),
                (
                    "usage_conditions_text",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="เงื่อนไขการใช้งานอื่นๆ (ตอน Archive)",
                    ),
                ),
                (
                    "license_agreement_file",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ไฟล์ข้อตกลงสิทธิ์การใช้งาน (ตอน Archive)",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database_subscription.vendor",
                        verbose_name="ผู้ขาย (ตอน Archive)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติฐานข้อมูลรายปี",
                "verbose_name_plural": "ประวัติฐานข้อมูลรายปี",
                "ordering": ["-year", "DB_Name"],
                "unique_together": {("database_subscription_id", "year")},
            },
        ),
        migrations.CreateModel(
            name="UsageStatisticsArchive",
            fields=[
                (
                    "USA_ID",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสสถิติการใช้งาน (Archive)",
                    ),
                ),
                ("archive_year", models.IntegerField(verbose_name="ปีที่ Archive")),
                (
                    "report_year",
                    models.IntegerField(verbose_name="ปีที่รายงาน (ตอน Archive)"),
                ),
                (
                    "report_month",
                    models.IntegerField(verbose_name="เดือนที่รายงาน (ตอน Archive)"),
                ),
                (
                    "total_item_requests",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนการเข้าถึงทั้งหมด (ตอน Archive)",
                    ),
                ),
                (
                    "unique_item_requests",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนการเข้าถึงที่ไม่ซ้ำ (ตอน Archive)",
                    ),
                ),
                (
                    "total_investigations",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนการสืบค้นทั้งหมด (ตอน Archive)",
                    ),
                ),
                (
                    "unique_investigations",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนการสืบค้นที่ไม่ซ้ำ (ตอน Archive)",
                    ),
                ),
                (
                    "limit_exceeded",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนการเข้าถึงเกินขีดจำกัด (ตอน Archive)",
                    ),
                ),
                (
                    "no_license",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนการเข้าถึงเนื่องจากไม่มี License (ตอน Archive)",
                    ),
                ),
                (
                    "regular_requests",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Regular Requests (ตอน Archive)",
                    ),
                ),
                (
                    "total_accesses",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Total Accesses (ตอน Archive)",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่ Archive"
                    ),
                ),
                (
                    "database_subscription_archive",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="database_subscription.usagestatisticsarchive",
                        verbose_name="ฐานข้อมูลที่บอกรับ (ตอน Archive)",
                    ),
                ),
            ],
            options={
                "verbose_name": "สถิติการใช้งาน (Archive)",
                "verbose_name_plural": "สถิติการใช้งาน (Archive)",
                "ordering": [
                    "archive_year",
                    "database_subscription_archive",
                    "-report_year",
                    "-report_month",
                ],
                "unique_together": {
                    (
                        "database_subscription_archive",
                        "report_year",
                        "report_month",
                        "archive_year",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="UsageStatistics",
            fields=[
                (
                    "US_ID",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสสถิติการใช้งาน",
                    ),
                ),
                ("report_year", models.IntegerField(verbose_name="ปีที่รายงาน")),
                ("report_month", models.IntegerField(verbose_name="เดือนที่รายงาน")),
                (
                    "total_item_requests",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="จำนวนการเข้าถึงทั้งหมด"
                    ),
                ),
                (
                    "unique_item_requests",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="จำนวนการเข้าถึงที่ไม่ซ้ำ"
                    ),
                ),
                (
                    "total_investigations",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="จำนวนการสืบค้นทั้งหมด"
                    ),
                ),
                (
                    "unique_investigations",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="จำนวนการสืบค้นที่ไม่ซ้ำ"
                    ),
                ),
                (
                    "limit_exceeded",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนการเข้าถึงเกินขีดจำกัด",
                    ),
                ),
                (
                    "no_license",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="จำนวนการเข้าถึงเนื่องจากไม่มี License",
                    ),
                ),
                (
                    "regular_requests",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Regular Requests"
                    ),
                ),
                (
                    "total_accesses",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Total Accesses"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่สร้าง"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="วันที่แก้ไขล่าสุด"
                    ),
                ),
                (
                    "database_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database_subscription.databasesubscription",
                        verbose_name="ฐานข้อมูลที่บอกรับ",
                    ),
                ),
            ],
            options={
                "verbose_name": "สถิติการใช้งาน (COUNTER R5)",
                "verbose_name_plural": "สถิติการใช้งาน (COUNTER R5)",
                "ordering": ["database_subscription", "-report_year", "-report_month"],
                "unique_together": {
                    ("database_subscription", "report_year", "report_month")
                },
            },
        ),
    ]
