# Generated by Django 4.2.20 on 2025-04-22 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseSubscription",
            fields=[
                (
                    "DS_ID",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID ฐานข้อมูล"
                    ),
                ),
                (
                    "DB_Name",
                    models.CharField(max_length=255, verbose_name="ชื่อฐานข้อมูล"),
                ),
                (
                    "DB_Collection",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Collection"
                    ),
                ),
                (
                    "DBJournal_List",
                    models.TextField(
                        blank=True, null=True, verbose_name="รายการวารสาร"
                    ),
                ),
                (
                    "DBEBook_List",
                    models.TextField(
                        blank=True, null=True, verbose_name="รายการ E-Book"
                    ),
                ),
                (
                    "FinMnm_ID",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID การจัดการการเงิน"
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้งานที่เกี่ยวข้อง",
                    ),
                ),
            ],
            options={
                "verbose_name": "ฐานข้อมูลที่บอกรับ",
                "verbose_name_plural": "ฐานข้อมูลที่บอกรับ",
            },
        ),
    ]
