# Generated by Django 4.2.20 on 2025-05-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_subscription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="subscription",),
        migrations.AlterUniqueTogether(name="usagestatistics", unique_together=None,),
        migrations.RemoveField(
            model_name="usagestatistics", name="database_subscription",
        ),
        migrations.AlterUniqueTogether(
            name="usagestatisticsarchive", unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usagestatisticsarchive", name="database_subscription_archive",
        ),
        migrations.DeleteModel(name="VendorArchive",),
        migrations.AlterUniqueTogether(
            name="yearlydatabasesubscriptionarchive", unique_together=None,
        ),
        migrations.RemoveField(
            model_name="yearlydatabasesubscriptionarchive", name="vendor",
        ),
        migrations.RemoveField(model_name="databasesubscription", name="Vendor_ID",),
        migrations.RemoveField(model_name="databasesubscription", name="is_active",),
        migrations.RemoveField(
            model_name="databasesubscription", name="service_level_operations",
        ),
        migrations.RemoveField(model_name="databasesubscription", name="subscribers",),
        migrations.AddField(
            model_name="databasesubscription",
            name="amount_original_currency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="จำนวนเงิน (สกุลเงินต้นทาง)",
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="amount_paid_thb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="จำนวนเงินที่ชำระ (บาท)",
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="budget_allocated",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="งบประมาณที่ตั้งเบิก",
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่ชำระเงิน"
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="payment_method",
            field=models.CharField(
                default="wire transfer",
                editable=False,
                max_length=20,
                verbose_name="วิธีการชำระเงิน",
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="renewal_year",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ปีที่บอกรับ"
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("expired", "หมดอายุ (บอกรับปีก่อนหน้า)"),
                    ("current", "กำลังบอกรับอยู่ในปัจจุบัน"),
                    ("future", "กำลังจะบอกรับในอนาคต"),
                ],
                default="current",
                max_length=20,
                verbose_name="สถานะการบอกรับ",
            ),
        ),
        migrations.AlterField(
            model_name="databasesubscription",
            name="has_perpetual_license",
            field=models.BooleanField(
                default=False, verbose_name="มีสิทธิ์ perpetual license"
            ),
        ),
        migrations.AlterField(
            model_name="databasesubscription",
            name="perpetual_license_terms",
            field=models.TextField(
                blank=True, null=True, verbose_name="เงื่อนไข perpetual license"
            ),
        ),
        migrations.AlterField(
            model_name="databasesubscription",
            name="usage_conditions_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="เงื่อนไขการใช้งานอื่น ๆ "
            ),
        ),
        migrations.DeleteModel(name="Payment",),
        migrations.DeleteModel(name="ServiceLevelOperation",),
        migrations.DeleteModel(name="Subscriber",),
        migrations.DeleteModel(name="UsageStatistics",),
        migrations.DeleteModel(name="UsageStatisticsArchive",),
        migrations.DeleteModel(name="Vendor",),
        migrations.DeleteModel(name="YearlyDatabaseSubscriptionArchive",),
    ]
