# Generated by Django 4.2.20 on 2025-04-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_subscription", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="databasesubscription", name="User_ID",),
        migrations.AddField(
            model_name="databasesubscription",
            name="coverage_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่สิ้นสุด Coverage"
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="coverage_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่เริ่มต้น Coverage"
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="publisher",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="สำนักพิมพ์"
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="renewal_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่ต่ออายุ"),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("pending", "Pending Renewal"),
                ],
                default="active",
                max_length=50,
                verbose_name="สถานะการบอกรับ",
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="subscription_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่สิ้นสุดสัญญา"
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="subscription_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="วันที่เริ่มต้นสัญญา"
            ),
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
    ]
