# Generated by Django 4.2.20 on 2025-04-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database_subscription", "0002_remove_databasesubscription_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databasesubscription", name="coverage_end_date",
        ),
        migrations.RemoveField(
            model_name="databasesubscription", name="coverage_start_date",
        ),
        migrations.RemoveField(model_name="databasesubscription", name="publisher",),
        migrations.RemoveField(model_name="databasesubscription", name="url",),
    ]
