# Generated by Django 4.2.20 on 2025-05-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "database_subscription",
            "0003_databasesubscription_original_currency_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="databasesubscription", name="DBEBook_List",),
        migrations.RemoveField(
            model_name="databasesubscription", name="DBJournal_List",
        ),
        migrations.CreateModel(
            name="CollectionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "journal_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="จำนวน E-Journals"
                    ),
                ),
                (
                    "ebook_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="จำนวน E-Books"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database_subscription.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "database_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_details",
                        to="database_subscription.databasesubscription",
                        verbose_name="ฐานข้อมูล",
                    ),
                ),
            ],
            options={
                "verbose_name": "รายละเอียด Collection",
                "verbose_name_plural": "รายละเอียด Collections",
                "unique_together": {("database_subscription", "collection")},
            },
        ),
    ]
