# Generated by Django 4.2.20 on 2025-04-23 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database_subscription', '0003_remove_databasesubscription_coverage_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('Usage_ID', models.AutoField(db_column='Usage_ID', primary_key=True, serialize=False, verbose_name='รหัสของการบันทึกข้อมูลการใช้งาน')),
                ('Usage_Count', models.IntegerField(db_column='Usage_Count', default=0, verbose_name='จำนวนการใช้งานฐานข้อมูล')),
                ('Usage_Type', models.CharField(blank=True, db_column='Usage_Type', max_length=255, null=True, verbose_name='ประเภทของการใช้งานฐานข้อมูล')),
                ('Usage_HistoryDate', models.DateTimeField(db_column='Usage_HistoryDate', verbose_name='วันเวลาที่มีการใช้งาน')),
                ('year', models.IntegerField(verbose_name='ปีที่ใช้งาน')),
            ],
            options={
                'verbose_name': 'รายงานสถิติการใช้งาน',
                'verbose_name_plural': 'รายงานสถิติการใช้งาน',
                'db_table': 'Usage_Statistics',
            },
        ),
        migrations.AlterModelOptions(
            name='databasesubscription',
            options={'ordering': ['created_at'], 'verbose_name': 'ฐานข้อมูลที่บอกรับ', 'verbose_name_plural': 'ฐานข้อมูลที่บอกรับ'},
        ),
        migrations.RemoveField(
            model_name='databasesubscription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='databasesubscription',
            name='status',
        ),
        migrations.AddField(
            model_name='databasesubscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='databasesubscription',
            name='DBEBook_List',
            field=models.TextField(blank=True, db_column='DBEBook_List', null=True, verbose_name='จำนวนชื่อเรื่องแบบ E-Books'),
        ),
        migrations.AlterField(
            model_name='databasesubscription',
            name='DBJournal_List',
            field=models.TextField(blank=True, db_column='DBJournal_List', null=True, verbose_name='จำนวนชื่อเรื่องแบบวารสาร'),
        ),
        migrations.AlterField(
            model_name='databasesubscription',
            name='DB_Collection',
            field=models.CharField(blank=True, db_column='DB_Collection', max_length=255, null=True, verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='databasesubscription',
            name='DB_Name',
            field=models.CharField(db_column='DB_Name', max_length=255, verbose_name='ชื่อฐานข้อมูล'),
        ),
        migrations.AlterField(
            model_name='databasesubscription',
            name='DS_ID',
            field=models.AutoField(db_column='DS_ID', primary_key=True, serialize=False, verbose_name='รหัสของฐานข้อมูล'),
        ),
    ]
