# Generated by Django 4.2.20 on 2025-05-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database_subscription",
            "0004_remove_databasesubscription_dbebook_list_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="collectiondetail", unique_together=set(),),
        migrations.RemoveField(model_name="databasesubscription", name="collections",),
        migrations.AddField(
            model_name="collectiondetail",
            name="collection_name",
            field=models.CharField(
                default="Default Collection Name",
                max_length=255,
                verbose_name="ชื่อ Collection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="databasesubscription",
            name="raw_collections_data",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="ข้อมูล Collections (ชื่อ, วารสาร, E-Books ต่อบรรทัด)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectiondetail",
            unique_together={("database_subscription", "collection_name")},
        ),
        migrations.RemoveField(model_name="collectiondetail", name="collection",),
    ]
