# Generated by Django 4.2.20 on 2025-04-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_subscription', '0004_usagestatistics_alter_databasesubscription_options_and_more'),
        ('financial_mnm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasesubscription',
            name='FinMnm_ID',
            field=models.ForeignKey(db_column='FinMnm_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_subscriptions', to='financial_mnm.financialmanagement', verbose_name='รหัสการจัดการการเงิน'),
        ),
        migrations.AlterField(
            model_name='databasesubscription',
            name='renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='กำหนดการต่ออายุการบอกรับ'),
        ),
        migrations.AlterField(
            model_name='databasesubscription',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดการบอกรับ'),
        ),
        migrations.AlterField(
            model_name='databasesubscription',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มต้นการบอกรับ'),
        ),
        migrations.AlterModelTable(
            name='databasesubscription',
            table='Database_Subscription',
        ),
        migrations.AddField(
            model_name='usagestatistics',
            name='database_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_subscription.databasesubscription', verbose_name='ฐานข้อมูลที่ใช้งาน'),
        ),
    ]
