# Generated by Django 4.2.20 on 2025-05-09 06:42

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        (
            "database_subscription",
            "0005_alter_collectiondetail_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="databasesubscription",
            options={
                "ordering": ["DB_Name", "-renewal_year"],
                "verbose_name": "ฐานข้อมูลที่บอกรับ",
                "verbose_name_plural": "ฐานข้อมูลที่บอกรับ",
            },
        ),
        migrations.AlterUniqueTogether(name="collectiondetail", unique_together=set(),),
        migrations.AddField(
            model_name="collectiondetail",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="database_subscription.collection",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectiondetail",
            unique_together={("database_subscription", "collection")},
        ),
        migrations.RemoveField(model_name="collectiondetail", name="collection_name",),
    ]
