# Generated by Django 4.2.20 on 2025-04-23 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial_mnm', '0002_calendarevent'),
        ('database_subscription', '0005_alter_databasesubscription_finmnm_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageStatisticsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่/เวลาที่ Archive')),
                ('Usage_Count', models.IntegerField(db_column='Usage_Count', default=0, verbose_name='จำนวนการใช้งานฐานข้อมูล (ตอน Archive)')),
                ('Usage_Type', models.CharField(blank=True, db_column='Usage_Type', max_length=255, null=True, verbose_name='ประเภทของการใช้งานฐานข้อมูล (ตอน Archive)')),
                ('Usage_HistoryDate', models.DateTimeField(db_column='Usage_HistoryDate', verbose_name='วันเวลาที่มีการใช้งาน (ตอน Archive)')),
                ('year', models.IntegerField(verbose_name='ปีที่ใช้งาน (ตอน Archive)')),
                ('database_subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database_subscription.databasesubscription', verbose_name='ฐานข้อมูลที่ใช้งาน (ตอน Archive)')),
                ('usage_statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='database_subscription.usagestatistics', verbose_name='รหัสของการบันทึกข้อมูลการใช้งาน')),
            ],
            options={
                'verbose_name': 'ประวัติรายงานสถิติการใช้งาน',
                'verbose_name_plural': 'ประวัติรายงานสถิติการใช้งาน',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseSubscriptionArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่/เวลาที่ Archive')),
                ('DB_Name', models.CharField(db_column='DB_Name', max_length=255, verbose_name='ชื่อฐานข้อมูล (ตอน Archive)')),
                ('DB_Collection', models.CharField(blank=True, db_column='DB_Collection', max_length=255, null=True, verbose_name='Collection (ตอน Archive)')),
                ('DBJournal_List', models.TextField(blank=True, db_column='DBJournal_List', null=True, verbose_name='จำนวนชื่อเรื่องแบบวารสาร (ตอน Archive)')),
                ('DBEBook_List', models.TextField(blank=True, db_column='DBEBook_List', null=True, verbose_name='จำนวนชื่อเรื่องแบบ E-Books (ตอน Archive)')),
                ('subscription_start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มต้นการบอกรับ (ตอน Archive)')),
                ('subscription_end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดการบอกรับ (ตอน Archive)')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='กำหนดการต่ออายุการบอกรับ (ตอน Archive)')),
                ('FinMnm_ID', models.ForeignKey(db_column='FinMnm_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='financial_mnm.financialmanagement', verbose_name='รหัสการจัดการการเงิน (ตอน Archive)')),
                ('database_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='database_subscription.databasesubscription', verbose_name='รหัสของฐานข้อมูล')),
            ],
            options={
                'verbose_name': 'ประวัติฐานข้อมูลที่บอกรับ',
                'verbose_name_plural': 'ประวัติฐานข้อมูลที่บอกรับ',
                'ordering': ['-archived_at'],
            },
        ),
    ]
