# Generated by Django 4.2.20 on 2025-04-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_subscription', '0006_usagestatisticsarchive_databasesubscriptionarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesubscriptionarchive',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='ปี'),
        ),
    ]
