# Generated by Django 4.2.20 on 2025-05-09 07:59

from django.db import migrations, models

def set_default_collection_name(apps, schema_editor):
    CollectionDetail = apps.get_model('database_subscription', 'CollectionDetail')
    for detail in CollectionDetail.objects.all():
        if not detail.collection_name and detail.database_subscription:
            detail.collection_name = detail.database_subscription.DB_Name
            detail.save()

class Migration(migrations.Migration):

    dependencies = [
        ("database_subscription", "0006_alter_databasesubscription_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="collectiondetail", unique_together=set(),),
        migrations.AddField(
            model_name="collectiondetail",
            name="collection_name",
            field=models.CharField(
                default="TEMP_DEFAULT", max_length=255, verbose_name="ชื่อ Collection"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="collectiondetail",
            unique_together={("database_subscription", "collection_name")},
        ),
        migrations.RemoveField(model_name="collectiondetail", name="collection",),

        migrations.RunPython(set_default_collection_name),

    ]
