# Generated by Django 4.2.20 on 2025-05-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database_subscription",
            "0007_alter_collectiondetail_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectiondetail",
            name="collection_name",
            field=models.CharField(max_length=255, verbose_name="ชื่อ Collection"),
        ),
        migrations.AlterField(
            model_name="databasesubscription",
            name="concurrent_users",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="จำนวนผู้ใช้งานพร้อมกัน",
            ),
        ),
    ]
