# Generated by Django 4.2.20 on 2025-04-30 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("database_subscription", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="คำค้นหา"
                    ),
                ),
                (
                    "result_count",
                    models.IntegerField(default=0, verbose_name="จำนวนผลลัพธ์"),
                ),
                (
                    "database_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database_subscription.databasesubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "การค้นหาฐานข้อมูล",
                "verbose_name_plural": "การค้นหาฐานข้อมูล",
                "db_table": "database_search",
            },
        ),
    ]
