# Generated by Django 4.2.20 on 2025-05-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "บรรณารักษ์สูงสุด"),
                    ("librarian", "บรรณารักษ์"),
                    ("staff", "เจ้าหน้าที่"),
                    ("user", "ผู้ใช้งานทั่วไป"),
                ],
                default="user",
                max_length=20,
                verbose_name="บทบาท",
            ),
        ),
    ]
