# Generated by Django 4.2.20 on 2025-04-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database_subscription', '0004_usagestatistics_alter_databasesubscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('Funder_ID', models.AutoField(db_column='Funder_ID', primary_key=True, serialize=False, verbose_name='รหัสผู้ให้ทุน')),
                ('Funder_Name', models.CharField(db_column='Funder_Name', max_length=255, verbose_name='ชื่อผู้ให้ทุน')),
                ('Funder_Budget', models.DecimalField(db_column='Funder_Budget', decimal_places=2, default=0.0, max_digits=15, verbose_name='งบประมาณที่ได้รับ')),
                ('Funder_History', models.TextField(blank=True, db_column='Funder_History', null=True, verbose_name='ประวัติการให้ทุน')),
            ],
            options={
                'verbose_name': 'ผู้ให้ทุน',
                'verbose_name_plural': 'ข้อมูลผู้ให้ทุน',
                'db_table': 'Funder',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('Vendor_ID', models.AutoField(db_column='Vendor_ID', primary_key=True, serialize=False, verbose_name='รหัสผู้ขาย')),
                ('Vendor_Name', models.CharField(db_column='Vendor_Name', max_length=255, verbose_name='ชื่อผู้ขาย')),
                ('Vendor_Contact', models.TextField(blank=True, db_column='Vendor_Contact', null=True, verbose_name='ข้อมูลการติดต่อ')),
                ('Vendor_Paycon', models.TextField(blank=True, db_column='Vendor_Paycon', null=True, verbose_name='ข้อตกลงการจ่ายเงิน')),
            ],
            options={
                'verbose_name': 'ผู้ขาย',
                'verbose_name_plural': 'ข้อมูลผู้ขาย',
                'db_table': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(db_column='Payment_ID', primary_key=True, serialize=False, verbose_name='รหัสการชำระเงิน')),
                ('Payment_Date', models.DateField(db_column='Payment_Date', verbose_name='วันที่ชำระเงิน')),
                ('Payment_Amount', models.DecimalField(db_column='Payment_Amount', decimal_places=2, max_digits=10, verbose_name='จำนวนเงินที่ชำระ')),
                ('Payment_Method', models.CharField(db_column='Payment_Method', max_length=255, verbose_name='วิธีการชำระเงิน')),
                ('payment_document', models.FileField(blank=True, null=True, upload_to='payments/', verbose_name='เอกสารการชำระเงิน')),
                ('currency', models.CharField(default='THB', max_length=3, verbose_name='สกุลเงิน')),
                ('Vendor_ID', models.ForeignKey(db_column='Vendor_ID', on_delete=django.db.models.deletion.CASCADE, to='financial_mnm.vendor', verbose_name='ผู้ขาย')),
                ('database_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_subscription.databasesubscription', verbose_name='ฐานข้อมูลที่บอกรับ')),
            ],
            options={
                'verbose_name': 'การชำระเงิน',
                'verbose_name_plural': 'ข้อมูลการชำระเงิน',
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='FinancialManagement',
            fields=[
                ('FinMnm_ID', models.AutoField(db_column='FinMnm_ID', primary_key=True, serialize=False, verbose_name='รหัสการจัดการการเงิน')),
                ('Negotiation_Details', models.TextField(blank=True, db_column='Negotiation_Details', null=True, verbose_name='รายละเอียดการเจรจาต่อรอง')),
                ('Perpetual_License', models.BooleanField(db_column='Perpetual_License', default=False, verbose_name='สัญญาซื้อขาด')),
                ('Usage_Terms', models.TextField(blank=True, db_column='Usage_Terms', null=True, verbose_name='ข้อกำหนดการใช้งาน')),
                ('Funder_ID', models.ForeignKey(db_column='Funder_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_mnm.funder', verbose_name='ผู้ให้ทุน')),
                ('Vendor_ID', models.ForeignKey(db_column='Vendor_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_mnm.vendor', verbose_name='ผู้ขาย')),
            ],
            options={
                'verbose_name': 'การจัดการการเงิน',
                'verbose_name_plural': 'ข้อมูลการจัดการการเงิน',
                'db_table': 'Financial_Management',
            },
        ),
    ]
