# Generated by Django 4.2.20 on 2025-04-30 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("database_subscription", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Funder",
            fields=[
                (
                    "Funder_ID",
                    models.AutoField(
                        db_column="Funder_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสผู้ให้ทุน",
                    ),
                ),
                (
                    "Funder_Name",
                    models.CharField(
                        db_column="Funder_Name",
                        max_length=255,
                        verbose_name="ชื่อผู้ให้ทุน",
                    ),
                ),
                (
                    "Contact_Person",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ผู้ติดต่อ"
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="อีเมล"
                    ),
                ),
                (
                    "Phone_Number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="เบอร์โทรศัพท์",
                    ),
                ),
                (
                    "Address",
                    models.TextField(blank=True, null=True, verbose_name="ที่อยู่"),
                ),
            ],
            options={
                "verbose_name": "ผู้ให้ทุน",
                "verbose_name_plural": "ผู้ให้ทุน",
                "db_table": "Funder",
                "ordering": ["Funder_Name"],
            },
        ),
        migrations.CreateModel(
            name="FunderArchive",
            fields=[
                (
                    "Funder_ID",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสผู้ให้ทุน (ตอน Archive)",
                    ),
                ),
                (
                    "Funder_Name",
                    models.CharField(
                        max_length=255, verbose_name="ชื่อผู้ให้ทุน (ตอน Archive)"
                    ),
                ),
                (
                    "Contact_Person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ผู้ติดต่อ (ตอน Archive)",
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="อีเมล (ตอน Archive)",
                    ),
                ),
                (
                    "Phone_Number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="เบอร์โทรศัพท์ (ตอน Archive)",
                    ),
                ),
                (
                    "Address",
                    models.TextField(
                        blank=True, null=True, verbose_name="ที่อยู่ (ตอน Archive)"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="วันที่/เวลาที่ Archive",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ปีที่ Archive"
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติผู้ให้ทุน",
                "verbose_name_plural": "ประวัติผู้ให้ทุน",
                "ordering": ["-archived_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialManagement",
            fields=[
                (
                    "FM_ID",
                    models.AutoField(
                        db_column="FM_ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสการจัดการงบประมาณ",
                    ),
                ),
                (
                    "Budget_Year",
                    models.IntegerField(
                        db_column="Budget_Year", verbose_name="ปีงบประมาณ"
                    ),
                ),
                (
                    "Total_Budget",
                    models.DecimalField(
                        db_column="Total_Budget",
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="งบประมาณทั้งหมด",
                    ),
                ),
                (
                    "Used_Budget",
                    models.DecimalField(
                        db_column="Used_Budget",
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="งบประมาณที่ใช้ไป",
                    ),
                ),
                (
                    "Remaining_Budget",
                    models.DecimalField(
                        db_column="Remaining_Budget",
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="งบประมาณคงเหลือ",
                    ),
                ),
                (
                    "funder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial_mnm.funder",
                        verbose_name="ผู้ให้ทุนที่เกี่ยวข้อง",
                    ),
                ),
                (
                    "subscriptions",
                    models.ManyToManyField(
                        blank=True,
                        to="database_subscription.databasesubscription",
                        verbose_name="การบอกรับฐานข้อมูลที่เกี่ยวข้อง",
                    ),
                ),
            ],
            options={
                "verbose_name": "การจัดการงบประมาณ",
                "verbose_name_plural": "การจัดการงบประมาณ",
                "db_table": "Financial_Management",
                "ordering": ["-Budget_Year"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="หัวข้อ")),
                ("date", models.DateField(verbose_name="วันที่")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="เวลา")),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้สร้าง",
                    ),
                ),
            ],
            options={
                "verbose_name": "กำหนดการส่วนกลาง",
                "verbose_name_plural": "ข้อมูลกำหนดการส่วนกลาง",
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="FinancialManagementArchive",
            fields=[
                (
                    "archive_id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="รหัสประวัติการจัดการงบประมาณ",
                    ),
                ),
                (
                    "fm_id",
                    models.IntegerField(
                        verbose_name="รหัสการจัดการงบประมาณ (ตอน Archive)"
                    ),
                ),
                (
                    "Budget_Year",
                    models.IntegerField(verbose_name="ปีงบประมาณ (ตอน Archive)"),
                ),
                (
                    "Total_Budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="งบประมาณทั้งหมด (ตอน Archive)",
                    ),
                ),
                (
                    "Used_Budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="งบประมาณที่ใช้ไป (ตอน Archive)",
                    ),
                ),
                (
                    "Remaining_Budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="งบประมาณคงเหลือ (ตอน Archive)",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="วันที่/เวลาที่ Archive",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="ปีที่ Archive")),
                (
                    "funder_archive",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial_mnm.funderarchive",
                        verbose_name="ผู้ให้ทุนที่เกี่ยวข้อง (ตอน Archive)",
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติการจัดการงบประมาณรายปี",
                "verbose_name_plural": "ประวัติการจัดการงบประมาณรายปี",
                "ordering": ["-year", "Budget_Year"],
                "unique_together": {("fm_id", "year")},
            },
        ),
    ]
