# Generated by Django 4.2.20 on 2025-05-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_mnm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="financialmanagement", name="funder",),
        migrations.RemoveField(model_name="financialmanagement", name="subscriptions",),
        migrations.AlterField(
            model_name="financialmanagement",
            name="Budget_Year",
            field=models.IntegerField(
                db_column="Budget_Year", unique=True, verbose_name="ปีงบประมาณ"
            ),
        ),
        migrations.DeleteModel(name="FinancialManagementArchive",),
        migrations.DeleteModel(name="Funder",),
        migrations.DeleteModel(name="FunderArchive",),
    ]
