# Generated by Django 4.2.20 on 2025-04-23 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_mnm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='หัวข้อ')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='เวลา')),
                ('note', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
            ],
            options={
                'verbose_name': 'กำหนดการส่วนกลาง',
                'verbose_name_plural': 'ข้อมูลกำหนดการส่วนกลาง',
                'ordering': ['date', 'time'],
            },
        ),
    ]
