# Generated by Django 4.2.20 on 2025-05-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_mnm", "0002_remove_financialmanagement_funder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialmanagement",
            name="Remaining_Budget",
            field=models.DecimalField(
                db_column="Remaining_Budget",
                decimal_places=2,
                max_digits=30,
                verbose_name="งบประมาณคงเหลือ",
            ),
        ),
        migrations.AlterField(
            model_name="financialmanagement",
            name="Total_Budget",
            field=models.DecimalField(
                db_column="Total_Budget",
                decimal_places=2,
                max_digits=30,
                verbose_name="งบประมาณทั้งหมด",
            ),
        ),
        migrations.AlterField(
            model_name="financialmanagement",
            name="Used_Budget",
            field=models.DecimalField(
                db_column="Used_Budget",
                decimal_places=2,
                default=0.0,
                max_digits=30,
                verbose_name="งบประมาณที่ใช้ไป",
            ),
        ),
    ]
